In [3]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [6]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [8]:
x.shape

torch.Size([2, 5])

In [9]:
y = torch.rand([2,5])
y

tensor([[0.0208, 0.3520, 0.6594, 0.6205, 0.5453],
        [0.1571, 0.9221, 0.3949, 0.4081, 0.4573]])

In [13]:
y = y.view([1,10])
y

tensor([[0.0208, 0.3520, 0.6594, 0.6205, 0.5453, 0.1571, 0.9221, 0.3949, 0.4081,
         0.4573]])